name: Scrape Woolies
on:
  push:
  schedule:
  - cron: "0 1 * * *"  # Daily at 1am UTC (12pm AEST)
env:
  AWS_REGION: ap-southeast-2
jobs:
  scrape-woolies:
    permissions:
      contents: read  # Required for checkout action
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -r requirements.txt
      - run: python3 woolies.py --quick
      - uses: actions/upload-artifact@v3
        with:
          name: woolies_all
          path: ./woolies_all.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ vars.TARGET_ROLE_ARN }}"
          aws-region: ap-southeast-2
      - run: aws s3 sync ./woolies/ s3://grocery-scrape-au/wooles/