name: Quick scrape test
on:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -r requirements.dev.txt
      - run: PYTHONPATH=. pytest -v tests
  scrape-woolies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -r requirements.txt
      - run: python3 main.py sync --quick woolies
      - uses: actions/upload-artifact@v3
        with:
          name: woolies_snapshot
          path: ./output/woolies/
  scrape-coles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -r requirements.txt
      - run: python3 main.py sync --quick coles
      - uses: actions/upload-artifact@v3
        with:
          name: coles_snapshot
          path: ./output/coles/